### ISSUE TITLE
next_level_name.py error for l3mapgen

### ISSUE THREAD

**Issue by aynur** [seadas/seadas#52]
Test case:

 /Users/Shared/seadas71/ocssw/run/scripts/ocssw_runner --ocsswroot /Users/Shared/seadas71/ocssw next_level_name.py /Users/Shared/test/scarla/A20151612015168.L3b_8D_OC l3mapgen --resolution=9km --suite=myprod --oformat=netCDF4

Error message:

Error!  Encountered UnboundLocalError:
Traceback (most recent call last):
  File "/Users/Shared/seadas71/ocssw/run/scripts/next_level_name.py", line 198, in main
    next_level_name = get_1_file_name(data_file, targ_prog, clopts)
  File "/Users/Shared/seadas71/ocssw/run/scripts/next_level_name.py", line 47, in get_1_file_name
    next_level_name = level_finder.get_next_level_name()
  File "/Users/Shared/seadas71/ocssw/run/scripts/modules/next_level_name_finder.py", line 1014, in get_next_level_name
    [self.next_level]()
  File "/Users/Shared/seadas71/ocssw/run/scripts/modules/next_level_name_finder.py", line 748, in _get_smigen_name
    smi_name += self.suite
UnboundLocalError: local variable 'smi_name' referenced before assignment

**Comment by MattElliottSeaDAS** [comment]
Fixed issue that was causing error with 8 day files.
