### ISSUE TITLE
ocssw needs fixing for EarthData login

### ISSUE THREAD

**Issue by j08lue** [seadas/seadas#98]
You announced earlier that data downloads will require EarthData login (https://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?pid=50346) and showed ways to tackle that for non-interactive downloads (https://oceancolor.gsfc.nasa.gov/data/download_methods/) which worked fine for me.

However, there are also OCSSW scripts that need fixing. You mention `getanc.py`  and `modis_atteph.py` on the forums (https://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?tid=11508).

But also something like the `ocssw/scripts` package is affected. For example, with seadas-7.5.2, I get the following error:

```python
Traceback (most recent call last):
  File "/home/bob/seadas-7.5.2/ocssw/scripts/modis_GEO.py", line 187, in <module>
    sys.exit(main())
  File "/home/bob/seadas-7.5.2/ocssw/scripts/modis_GEO.py", line 175, in main
    m.utcleap()
  File "/home/bob/seadas-7.5.2/ocssw/scripts/modules/modis_GEO_utils.py", line 140, in utcleap
    lut.get_luts()
  File "/home/bob/seadas-7.5.2/ocssw/scripts/modules/LutUtils.py", line 132, in get_luts
    regex='^((?!\d+).)*' + suffix, check_times=True)
  File "/home/bob/seadas-7.5.2/ocssw/scripts/modules/JsonUtils.py", line 272, in download_allfiles
    all_links = self.get_links(url, regex=regex)
  File "/home/bob/seadas-7.5.2/ocssw/scripts/modules/JsonUtils.py", line 238, in get_links
    content = response.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

Do you have a roadmap for fixing these issues yet?

**Comment by j08lue** [comment]
You could perhaps use `requests` for the calls that require authentication, with built-in support for `~/.netrc`. That could also simplify the code. It might require some tweaking of the session though, like we did in https://github.com/DHI-GRAS/earthdata-download/blob/6586904a7b8d5683cf403bd9b5a0589aca04d8c5/earthdata_download/download.py#L27, although there might be more elegant solutions.

I took the liberty to fork your `scripts` code here https://github.com/DHI-GRAS/seadas-ocssw-scripts and will take some attempts at fixing it. Unless you already are working on a solution?

Btw, it would be great to to have the `ocssw` code on GitHub, too, if you are interested in community help.

**Comment by j08lue** [comment]
I can see you already fixed this, actually using `requests`: https://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?tid=11598
